### PR TITLE
Release 0.12.12

### PR DESCRIPTION
**Pull request by jakirkham**
```
2017-12-05  0.12.12:
--------------------
  * bugfixes:
    - #6588 [typescript] Model references are not resolved when trying to change ranges and attach js callback at the same time
    - #7268 [component: bokehjs] [notebook] Push_notebook regression in 0.12.11
    - #7282 [component: bokehjs] Add missing return statements to get_indices typescript version
  * tasks:
    - #7214 [component: bokehjs] [component: build] Allow es6 output from bokehjs' build
    - #7276 Unclear exception when bokeh_log_level env variable is set to a wrong value
    - #7279 [component: docs] Configuring plot tools documentation was unclear
```

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by jakirkham** [comment]
Could you please review, @bryevdv?

**Comment by jakirkham** [comment]
Appears that `conda-build` is failing on Windows due to a missing `aux.d.ts` file during tarball extraction. There is no `aux.d.ts` in the repo, but there is an `aux.ts`. Not sure why the issue is absent on Linux. Traceback and link to the log included below.

<details>
<summary>Traceback:</summary>

```
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1524, in build_tree
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1062, in build
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 519, in provide
    unpack(metadata, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 91, in unpack
    tar_xf(src_path, config.work_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 342, in tar_xf
    t.extractall(path=dir_path.encode(codec))
  File "C:\Miniconda\lib\tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "C:\Miniconda\lib\tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Miniconda\lib\tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Miniconda\lib\tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: 'C:\\bld\\bokeh_1512537596535\\work\\bokeh-0.12.12\\bokeh\\server\\static\\js\\types\\core\\aux.d.ts'
```

</summary>

ref: https://ci.appveyor.com/project/conda-forge/bokeh-feedstock/build/1.0.43/job/kkm7hax3e2dq9v4q

**Comment by bryevdv** [comment]
Looks like there is a problem with installing the package on windows https://github.com/bokeh/bokeh/issues/7283 There will probably have to be a new release. I would plan to skip this release altogether.

**Comment by jakirkham** [comment]
Ok, I'll hold off. Thanks for the info.

**Comment by jakirkham** [comment]
Superceded by PR ( https://github.com/conda-forge/bokeh-feedstock/pull/19 ) releasing `bokeh` version `0.12.13` with a fix for the Windows build issue.

**Pull request closed without merging**
