### PR TITLE
NO MRG: Test 0.12.13rc1

### PR DESCRIPTION
**Pull request by jakirkham**
Tries building the `0.12.13rc1` release of `bokeh` to see if it fixes issues experienced on Windows. ( https://github.com/conda-forge/bokeh-feedstock/pull/16 ) ( https://github.com/bokeh/bokeh/issues/7283 )

cc @bryevdv

### CODE REVIEW

**Comment by bryevdv** [comment]
How long before appveyor jobs start?

**Comment by jakirkham** [comment]
Unfortunately doesn't look like it will start for ~5hrs (maybe a little less). Normally would be an hour or two, but looks like some `pyside2` builds are ahead of us and will take ~3hrs total.

**Comment by jakirkham** [comment]
Though could enable builds on my fork, which could give us faster results if that would help.

**Comment by bryevdv** [comment]
The conda packages, though they build, also have a related problem that causes `Tarfile` to blow up. We are still diagnosing.

**Comment by jakirkham** [comment]
Yep, am watching that issue. Will hold tight unless there is something you need me to do.

**Comment by jakirkham** [comment]
Though it is interesting as one might expect the testing phase would have demonstrated untarring the `conda` packages would prove problematic, which this didn't show interestingly. In any event, it is a moot point now. Closing this out.

**Pull request closed without merging**
