### PR TITLE
Bump version to 3.1.1

### PR DESCRIPTION
**Pull request by philippjfr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philippjfr** [comment]
@mattpap @bryevdv I haven't followed previous discussion here, it seems to be trying to build bokehjs from scratch and fails:

```

  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/conda/feedstock_root/build_artifacts/bokeh_1683541616843/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python /home/conda/feedstock_root/build_artifacts/bokeh_1683541616843/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpx36a3gpg
  cwd: /home/conda/feedstock_root/build_artifacts/bokeh_1683541616843/work
  Building wheel for bokeh (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for bokeh
Failed to build bokeh
ERROR: Could not build wheels for bokeh, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$PREFIX/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 426, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for bokeh, which is required to install pyproject.toml-based projects
```

**Comment by bryevdv** [comment]
It looks like they PR missed the mark by only skipping the check when an sdist itself is built, instead of when an sdist is used to build.

**Comment by bryevdv** [comment]
Well, actually, hold on, we verify that sdist install works on every CI job:

https://github.com/bokeh/bokeh/blob/branch-3.2/scripts/ci/verify_pip_install_using_sdist.sh

Why is conda-forge manually un-tarring the sdist instead of just installing it directly *That* is what is guaranteed to work.

**Comment by philippjfr** [comment]
@jakirkham Sorry to bother you but do you have any guidance here?

Separate issue but any objections to removing almarklein as a maintainer of this recipe?

**Comment by bryevdv** [comment]
@philippjfr can you change the recipe here to install the sdist tarball? Or to re-package the wheel? We can probably make `pip install . ` work inside an sdist, but not for 3.1.1.

**Comment by ocefpaf** [comment]
> @philippjfr can you change the recipe here to install the sdist tarball?

There should be no difference from the uncompressed source and the compressed one.  We need to figure out what are the differences in the CI setup upstream and what we do here.

> Or to re-package the wheel? We can probably make `pip install . ` work inside an sdist, but not for 3.1.1.

That is a last resort alternative for third party packagers. Let try to avoid this and figure out what is missing to make a proper build from the source.

**Comment by bryevdv** [comment]
> There should be no difference from the uncompressed source and the compressed one. 

I agree in principle, however you can plainly observe that `pip install <tarball>` works, and is verified to work, on every single Bokeh CI build job:

https://github.com/bokeh/bokeh/actions/runs/4928272398/jobs/8806416897?pr=13121#step:10:1

i.e. we've tried to do our due diligence here. I am more than happy to to add yet another check for `verify_pip_install_using_exploded_sdist` or whatever, but that is for the future. AFAIK Holoviews/Panel really needs a 3.1.1 release soon.

> That is a last resort alternative for third party packagers. Let try to avoid this and figure out what is missing to make a proper build from the source.

Just noting that I fundamentally disagree with the value or importance of this. Everyone's life would be much simpler if you would just re-package the official wheels the project itself publishes.

**Comment by ocefpaf** [comment]
> I agree in principle, however you can plainly observe that `pip install <tarball>` works, and is verified to work, on every single Bokeh CI build job:

You do have the git tags there in your tests. The tarball doesn't. That is the error we are having here.

> Just noting that I fundamentally disagree with the value or importance of this. Everyone's life would be much simpler if you would just re-package the official wheels the project itself publishes, that it intends to be the official source of truth for users.

You don't have to maintain this package if that is a burden to you. Also wheels are not the answer for everybody. We try to be inclusive and build packages in as many variants as we can instead of locking folks into a single option.

> Building" pure-python packages "from source" for conda packages add no value whatsoever. It is a waste of time and resources, in the best cases, and actively manufactures tedious and unpleasant busy-work for maintainers in the worst.

That is shortsighted as pure python packages still require a dependency management and many other details that don't make then as pure as you think. Bokeh, after all, packages way more than just Python.

**Comment by ocefpaf** [comment]
> Certainly, but re-packaging our wheel _works_ and switching to that method [1] would free me from having to worry about this approximately ever again. I suspect that would be true for great many packages, and that is my point.

It doesn't work in all environment scenarios. Glad it works for you but it is not a solution, otherwise we would've done it already. Please note that there are 100th of users and most of then use the conda environment management to get the  right versions for the conda package. Repackaging is last resort for pathological packages and are used with great caution.
 
> The question remains what can be done for this release.

What we with every broken release. Skip it or backport a patch with one exists.

**Comment by philippjfr** [comment]
Sorry I've been absent here, I'll try to resolve this but note I'm currently in Paris for JupyterCon and am preparing for a talk do it might not be until later tomorrow or Thursday until I can devote actual time here.

**Comment by ocefpaf** [comment]
> Literally nothing I propose has the effect of undermining conda dependency management in any way.

When you repackage you must follow the exact same dependencies in both worlds. That is not always true as third party packagers can and will adjust that to either limit or expand the possibilities. See the global pinning in conda-forge as one example. We do not care about a single package, we curate an ecosystem.

Sure your single use example is fine. As environments grow and users install more packages in them is when the problems appear. Again, 1 solution does not fit all cases.

**Comment by bryevdv** [comment]
> When you repackage you must follow the exact same dependencies in both worlds. 

Certainly not true. We derive the runtime dependencies in `meta.yaml` directly from `pyproject.toml` but they could be curated separately or manually, if need be. Even if that were the case here, it would still be preferable (to me).

>  Again, 1 solution does not fit all cases.

I never said such. I am saying it ought to be an option in cases where it does work. 

In any case I am beyond exhausted of this. I will work with the other Bokeh core devs to try to ensure that others can pick up any conda-forge concerns going forward.

**Comment by ocefpaf** [comment]
> Certainly not true. We derive the runtime dependencies in `meta.yaml` directly from `pyproject.toml` but they could be curated separately or manually, if need be. Even if that were the case here, it would still be preferable (to me).

You literally just said the same thing as I did!

> I never said such. I am saying it ought to be an option in cases where it does work.

Yet you insist we do that even though I mention many times it is not a solution for third party packagers.

> In any case I am beyond exhausted of this. I will work with the other Bokeh core devs to try to ensure that others can pick up any conda-forge concerns going forward.

Sure. Again, as I mentioned above, if maintaining this is a burden, just don't.

PS: It is not a conda-forge concern, it is a third party packager concern. If this sdist is used by homebrew, debian, fedora, etc, it will be broken there too. They probably just patch it too.

**Pull request merged**
