### PR TITLE
Version 0.12.6

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- bump to version 0.12.6
- remove patches which are fixed upstream

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @kmuehlbauer.

**Comment by jakirkham** [comment]
It looks like there is a new dependency, [`bkcharts >=0.2`]( https://github.com/bokeh/bokeh/blob/0.12.6/setup.py#L98 ). Could you please add it to `run`?

**Comment by kmuehlbauer** [comment]
@jakirkham Sorry, fat fingers... I also canceled first Travis and AppVeyor tasks.

**Comment by jakirkham** [comment]
No worries.

Yeah it looks like `bkcharts` is going to be an interesting package to make. Seems that `bkcharts` uses `bokeh` even though it doesn't depend on `bokeh` and as we now know `bokeh` requires `bkcharts`. 😕

**Comment by jakirkham** [comment]
So it looks like the `bokeh.charts.builders` import fails. The `builders` package is now part `bkcharts`. That said, based on the [code]( https://github.com/bokeh/bokeh/blob/0.12.6/bokeh/charts/__init__.py ) in `bokeh` and how `bkcharts` is [laid out]( https://github.com/bokeh/bkcharts/tree/0.2/bkcharts ), would have expected this to work. I suppose we could drop the import test, but from what I'm seeing not only should we not have to, but it should work. 😕 Thoughts on this import failure, @bryevdv?

**Comment by bryevdv** [comment]
My recommendation is to go light on testing (or do whatever you need to do in the short term) until Bokeh 1.0, at which point the dependencies will be reversed and made sensible. Also FYI we will be strongly promoting Holoviews as the preferred very high level interface for Bokeh, as it has very active development. The reality is that there is no one currently with bandwidth to do anything more with `bkcharts` Unless someone from the community wants to pick up development and maintenance of `bkcharts`, it is at a dead end (one of the reasons it was split off)

**Comment by kmuehlbauer** [comment]
`bkcharts` README says it is optional to `bokeh`. So why is `bkcharts` needed to run `bokeh`? Or do I get something wrong?

**Comment by bryevdv** [comment]
@kmuehlbauer `bkcharts` used to be `bokeh.charts` So for now, until Bokeh 1.0 is released`, the dependencies are "backwards" so that a compatibility shim in Bokeh (that will be removed at Bokeh 1.0) will "just work" i.e. it is the way it is so that `bokeh.charts` can be cleanly deprecated without immediately breaking the code of everyone that uses it.

**Comment by kmuehlbauer** [comment]
@bryevdv Thanks for the clarifications. But that leaves us with an unusable bokeh 0.12.6 version here on conda-forge, not? What can be done to get 0.12.6 into conda-forge?

**Comment by bryevdv** [comment]
> Thanks for the clarifications. But that leaves us with an unusable bokeh 0.12.6 version here on conda-forge, not? What can be done to get 0.12.6 into conda-forge?

The quickest solution would seem to be to just add `bkcharts` which is a pure python package that should be trivial to build.

**Comment by jakirkham** [comment]
Like this? 😉

xref: https://github.com/conda-forge/staged-recipes/pull/3131

**Comment by kmuehlbauer** [comment]
@jakirkham added `bkcharts` to conda-forge. But it depends on `bokeh`, so this creates some circular dependeny, which blows the whole thing. `bkcharts` is already added here as run dependency, but still this fails somehow.

**Comment by bryevdv** [comment]
`bkcharts` should not depend on `bokeh` for now, just like the official `bkcharts` does not depend on `bokeh` (for now). Full stop. There is no reason right now why anyone should or would reasonably try to install `bkcharts` without `bokeh`, and installing `bokeh` will bring in `bkcharts` automatically. I know this sucks. I promise it's the best solution available out of a field of worse ones.

**Comment by bryevdv** [comment]
Or perhaps more directly: you should do what ever you need to do (disable tests, whatever) in the short term in order to:
* add `bkcharts`
* not have it depend on `bokeh`

**Comment by jakirkham** [comment]
It doesn't. However we need `bokeh` as a test dependency at least. There is no way around this as testing is required in conda-forge and we can't so much as run `import bkcharts` without having `bokeh` 0.12.6.

**Comment by bryevdv** [comment]
> It doesn't. However we need bokeh as a test dependency at least. There is no way around this as testing is required in conda-forge and we can't so much as run import bkcharts without having bokeh 0.12.6.

I am afraid I don't have a solution for you then. `bkcahrts` is not truly "it's own" package yet, and won't be until Bokeh 1.0 is released. The only I can imagine alternative is that you patch Bokeh to remove the compat shim in the C-F version, then you can make the dependencies "correct"

**Comment by bryevdv** [comment]
What are your minimum tests? Just that `import bkcharts` works? Great, patch `bkcharts/__init__.py` so that everything in it is inside a `try/except` block that just passes on import error. Also a terrible solution but perhaps relatively less so.

**Comment by jakirkham** [comment]
Honestly I see that as little better than having no tests at all. If the user wishes not to test the package, they can disable the tests when building with `conda-build`. FWIW that PR is passing currently.

**Comment by bryevdv** [comment]
I agree its no better in practice, I was only suggesting it as a 'technically correct" response to:

> There is no way around this as testing is required in conda-forge

**Comment by kmuehlbauer** [comment]
@jakirkham How do we proceed? I'm a bit at loss atm.

**Comment by jakirkham** [comment]
Sure, so the failure appears to be caused by one of the import tests. In particular, importing `bokeh.charts.builders` is causing the failure. Given as this import has been moved to `bkcharts` and is not included in `bkcharts` top-level module, I believe this is causing the failure. We have a few options (listed below).

1. Comment that import test. (should pass then we merge)
2. Patch an import in `bkcharts` at `staged-recipes`. (once `bkcharts` is in restart CI and merge here)
3. Patch `bkcharts` proper to fix the import. (once `bkcharts` is fixed we should be good to go)

Personally I'm fine with any of these. Doing 1 should be easy and would recommend that. Am also ok taking on 2 and upstreaming the patch and will probably do something like this anyways.

**Comment by jakirkham** [comment]
After investigating other options, I think now that 1 is the only viable one. Please delete the `bokeh.charts.builders` import test as this doesn't and FWICT will not work correctly with how `bokeh` and `bkcharts` are setup currently.

**Comment by kmuehlbauer** [comment]
@jakirkham After removing the colliding import test, the CI's are happy. So this is ready for merge, then.

**Comment by jakirkham** [comment]
Thanks @kmuehlbauer.

**Comment by bryevdv** [comment]
🎊

**Pull request merged**
